[package]
name = "perionav"
version = "0.1.0"
edition = "2021"

[dependencies]
ordered-float = "3.7.0"
rand = "0.8.5"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
rstest = "0.17.0"

[[bench]]
name = "my_benchmark"
harness = false
